#' Synthetic x Opata genetic map, 88 DH lines
#' 
#' A dataframe containing the chromosome, physical position, and genetic
#' position of SNPs generated by a PstI-MspI double digest 
#' genotyping-by-sequencing (GBS) protocol, comparing physical positions of SNPs
#' in the International Wheat Genome Sequencing Consortium (IWGSC) v1.0 
#' Chinese Spring wheat Reference Sequence against genetic positions in a
#' population of 88 doubled-haploid lines derived from the Synthetic x Opata
#' cross. SNPs that mapped to different chromsomes in Chinese Spring and the
#' Synthetic x Opata cross have been removed, along with four outliers.
#' 
#' @format A data frame with 7,742 rows and 3 variables:
#' \describe{
#'    \item{chr}{chromosome name}
#'    \item{dist}{genetic position, in centiMorgans (cM)}
#'    \item{pos}{phyiscal position, in base pairs (bp)}
#' }
#' @source \url{https://urgi.versailles.inra.fr/download/iwgsc/IWGSC_RefSeq_Annotations/v1.0/iwgsc_refseqv1.0_SynOpRIL993_GBS.zip}
"synop_dh88"