#' Synthetic x Opata genetic map, 88 DH lines
#' 
#' A dataframe containing map data on SNPs generated by a PstI-MspI double digest 
#' genotyping-by-sequencing (GBS) protocol, with physical positions from 
#' the International Wheat Genome Sequencing Consortium (IWGSC) v1.0 
#' Chinese Spring wheat Reference Sequence and genetic positions derived from a
#' population of 88 doubled-haploid (DH) lines descended from the Synthetic x Opata
#' cross. SNPs that mapped to different chromosomes in Chinese Spring and the
#' Synthetic x Opata cross have been removed, along with four outliers.
#' 
#' This data is in the format required for PLINK .map files. However, note that
#' many programs that use PLINK files may require the header to be removed, and
#' may require genetic distances to be converted to Morgans.
#' 
#' @format A data frame with 7,742 rows and 4 variables:
#' \describe{
#'    \item{chr}{chromosome name}
#'    \item{id}{SNP identifier}
#'    \item{dist}{genetic position, in centiMorgans (cM)}
#'    \item{pos}{phyiscal position, in base pairs (bp)}
#' }
#' @source \url{https://urgi.versailles.inra.fr/download/iwgsc/IWGSC_RefSeq_Annotations/v1.0/iwgsc_refseqv1.0_SynOpRIL993_GBS.zip}
"synop_dh88"

#' Synthetic x Opata genetic map, 173 RIL lines
#' 
#' A dataframe containing map data on SNPs generated by a PstI-MspI double digest 
#' genotyping-by-sequencing (GBS) protocol, with physical positions from 
#' the International Wheat Genome Sequencing Consortium (IWGSC) v1.0 
#' Chinese Spring wheat Reference Sequence and genetic positions derived from a
#' population of 173 recombinant inbred lines (RILs) descended from the 
#' Synthetic x Opata cross. SNPs that mapped to different chromosomes in Chinese 
#' Spring and the Synthetic x Opata cross have been removed, along with three 
#' outliers.
#' 
#' This data is in the format required for PLINK .map files. However, note that
#' many programs that use PLINK files may require the header to be removed, and
#' may require genetic distances to be converted to Morgans.
#' 
#' @format A data frame with 4,027 rows and 3 variables:
#' \describe{
#'    \item{chr}{chromosome name}
#'    \item{id}{SNP identifier}
#'    \item{dist}{genetic position, in centiMorgans (cM)}
#'    \item{pos}{phyiscal position, in base pairs (bp)}
#' }
#' @source \url{https://urgi.versailles.inra.fr/download/iwgsc/IWGSC_RefSeq_Annotations/v1.0/iwgsc_refseqv1.0_SynOpRIL993_GBS.zip}
"synop_ril173"